"use client";
import { useState } from "react";

type Lead = { id: string; name: string; phone: string; email: string; date: string; status: string; notes: string };
const blank: Lead = { id: "", name: "", phone: "", email: "", date: "", status: "tentative", notes: "" };

export default function AdminTools() {
  const [leads, setLeads] = useState<Lead[]>(() => { if (typeof window === "undefined") return []; try { return JSON.parse(localStorage.getItem("keeanu-leads") || "[]"); } catch { return []; } }); const [lead, setLead] = useState(blank); const [tab, setTab] = useState("calendar");
  function saveLead(event: React.FormEvent) { event.preventDefault(); const item = { ...lead, id: lead.id || crypto.randomUUID() }; const next = [item, ...leads.filter((x) => x.id !== item.id)]; setLeads(next); localStorage.setItem("keeanu-leads", JSON.stringify(next)); setLead(blank); }
  const sorted = [...leads].sort((a,b) => a.date.localeCompare(b.date));
  return <section className="admin-tools"><header className="inbox-heading"><div><p className="eyebrow">Operations</p><h2>Seguimiento de parejas</h2></div><div className="tool-tabs"><button onClick={() => setTab("calendar")} aria-pressed={tab === "calendar"}>Calendario</button><button onClick={() => setTab("leads")} aria-pressed={tab === "leads"}>Prospectos</button><button onClick={() => setTab("quote")} aria-pressed={tab === "quote"}>Cotización</button></div></header>
    {tab === "calendar" && <div className="admin-calendar"><p className="muted">Fechas reservadas y tentativas registradas en el panel.</p>{sorted.length ? sorted.map((item) => <article key={item.id}><time>{item.date || "Sin fecha"}</time><strong>{item.name}</strong><span>{item.status === "reserved" ? "Reservada" : "Tentativa"}</span></article>) : <p className="empty-card">Todavía no hay fechas registradas.</p>}</div>}
    {tab === "leads" && <div className="lead-layout"><form onSubmit={saveLead}><label>Nombre<input required value={lead.name} onChange={(e) => setLead({...lead,name:e.target.value})}/></label><label>Celular<input value={lead.phone} onChange={(e) => setLead({...lead,phone:e.target.value})}/></label><label>Correo<input type="email" value={lead.email} onChange={(e) => setLead({...lead,email:e.target.value})}/></label><label>Fecha<input type="date" value={lead.date} onChange={(e) => setLead({...lead,date:e.target.value})}/></label><label>Estado<select value={lead.status} onChange={(e) => setLead({...lead,status:e.target.value})}><option value="tentative">Tentativa</option><option value="reserved">Reservada</option></select></label><label>Notas<textarea rows={4} value={lead.notes} onChange={(e) => setLead({...lead,notes:e.target.value})}/></label><button type="submit">Guardar prospecto</button></form><div className="lead-list">{leads.map((item) => <article key={item.id}><strong>{item.name}</strong><span>{item.date || "Sin fecha"} · {item.status === "reserved" ? "Reservada" : "Tentativa"}</span><button onClick={() => setLead(item)}>Editar</button></article>)}</div></div>}
    {tab === "quote" && <div className="quote-builder"><p className="muted">Completa los datos y usa “Descargar PDF” para guardar o enviar la propuesta.</p><label>Pareja<input id="quote-couple" placeholder="Ana & Adrian"/></label><label>Fecha y lugar<input id="quote-place" placeholder="24 de octubre · Guasave, Sinaloa"/></label><label>Propuesta<textarea id="quote-detail" rows={7} placeholder="Cobertura, entregables, tiempos y extras..."/></label><button onClick={() => window.print()}>Descargar PDF</button></div>}
  </section>;
}
