import Link from "next/link";
import { notFound } from "next/navigation";

const pages: Record<string, { eyebrow: string; title: string; intro: string; items: Array<[string, string]> }> = {
  proceso: { eyebrow: "Cómo trabajamos", title: "Una forma tranquila de llegar al día.", intro: "Los acompañamos desde la primera conversación hasta que vuelven a abrir sus recuerdos.", items: [["Nos conocemos", "Escuchamos cómo imaginan su boda y qué momentos quieren conservar."], ["Planeamos juntos", "Les orientamos con tiempos, luz y espacios para que todo fluya sin posar de más."], ["Vivimos la historia", "Retratamos y grabamos lo que sucede al natural: gestos, voces, pausas y celebración."], ["La vuelven a sentir", "Reciben una colección cuidada para regresar a ese día durante muchos años."]] },
  paquetes: { eyebrow: "Paquetes base", title: "El punto de partida para su historia.", intro: "Comenzamos con lo que necesitan y construimos una propuesta alrededor de su celebración. Los precios se comparten al conversar sobre su fecha.", items: [["Colección Uno", "Dos fotógrafos y dos videógrafos. Save the date, maquillaje, first look, sesión de novios y familiar, misa y recepción. Entrega de recuerdos editados, archivos en alta resolución y galería web."], ["Colección Dos", "Un fotógrafo y un videógrafo. Save the date, sesión de novios, first look, misa y recepción. Incluye entrega editada de foto y video, archivos en alta resolución y galería web."], ["Colección Tres", "Un fotógrafo y un videógrafo para sesión de novios, misa y recepción. Incluye selección editada de foto y video, archivos en alta resolución y galería web."], ["Detalles adicionales", "Podemos sumar horas de cobertura, un segundo fotógrafo, photobook o foto enmarcada según lo que necesiten."]] },
  faq: { eyebrow: "Preguntas frecuentes", title: "Antes de empezar, platiquemos.", intro: "Queremos que se sientan acompañados desde el primer mensaje.", items: [["¿En qué lugares trabajan?", "Keeanu nace en Sonora y cubre bodas en Sinaloa y otros destinos."], ["¿Con cuánto tiempo debemos reservar?", "Lo ideal es escribirnos en cuanto tengan fecha para acompañarles con calma."], ["¿Podemos contratar fotografía y video?", "Sí. Podemos contar su día con fotografías, video o ambos."], ["¿Nos ayudan a planear las fotos?", "Sí. Les guiamos cuando hace falta, cuidando que los momentos se sientan naturales."]] },
  testimonios: { eyebrow: "Palabras de parejas", title: "Lo que permanece después del día.", intro: "Historias vividas con calma, convertidas en recuerdos a los que se puede volver.", items: [["Pareja Keeanu · Sonora", "Nos sentimos acompañados desde la primera conversación. Las fotografías nos regresan a cada instante."], ["Pareja Keeanu · Sinaloa", "No tuvimos que actuar frente a la cámara. Keeanu estuvo atento a todo lo que estaba pasando."], ["Pareja Keeanu · Navojoa", "La entrega cuenta nuestra historia completa: los nervios, la familia, las risas y la celebración."]] },
};

export default async function InfoPage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug;
  const page = pages[slug]; if (!page) notFound();
  return <div className="story-page info-page"><header className="story-nav"><Link className="site-logo" href="/"><img className="site-logo-image" src="/keeanu-logo-square.png" alt="Keeanu Contreras" /></Link><Link href="/#trabajo">Portafolio</Link><div className="language-switch"><Link href="/">ES</Link><span>/</span><Link href="/en">EN</Link></div></header><main id="main"><section className="story-hero"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></section><div className="info-list">{page.items.map(([title, text], index) => <article className={slug === "paquetes" ? "info-card info-card-action" : "info-card"} key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h2>{title}</h2><p>{text}</p>{slug === "paquetes" && index < 3 && <Link className="info-card-link" href="/#contact">Solicitar esta colección</Link>}</div></article>)}</div><section className="story-end"><p>¿Te imaginas tu historia aquí?</p><Link className="arrow-link" href="/#contact">Hablemos</Link></section></main></div>;
}
